package in.credit.model;
// Generated Apr 24, 2015 9:08:10 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AccMaster generated by hbm2java
 */
public class AccMaster  implements java.io.Serializable {


     private Integer masterId;
     private Date fromDate;
     private Date toDate;
     private String firm;
     private String address;

    public AccMaster() {
    }

    public AccMaster(Date fromDate, Date toDate, String firm, String address) {
       this.fromDate = fromDate;
       this.toDate = toDate;
       this.firm = firm;
       this.address = address;
    }
   
    public Integer getMasterId() {
        return this.masterId;
    }
    
    public void setMasterId(Integer masterId) {
        this.masterId = masterId;
    }
    public Date getFromDate() {
        return this.fromDate;
    }
    
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }
    public Date getToDate() {
        return this.toDate;
    }
    
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
    public String getFirm() {
        return this.firm;
    }
    
    public void setFirm(String firm) {
        this.firm = firm;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


