package in.credit.model;
// Generated Apr 13, 2015 1:34:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AccountType generated by hbm2java
 */
public class AccountType  implements java.io.Serializable {


     private Integer typeId;
     private String typeName;
     private Set<Account> accounts = new HashSet<Account>(0);

    public AccountType() {
    }

	
    public AccountType(String typeName) {
        this.typeName = typeName;
    }
    public AccountType(String typeName, Set<Account> accounts) {
       this.typeName = typeName;
       this.accounts = accounts;
    }
   
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


