package in.credit.model;
// Generated Apr 24, 2015 9:08:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer cityId;
     private State state;
     private String cityName;
     private Set<Account> accounts = new HashSet<Account>(0);

    public City() {
    }

	
    public City(String cityName) {
        this.cityName = cityName;
    }
    public City(State state, String cityName, Set<Account> accounts) {
       this.state = state;
       this.cityName = cityName;
       this.accounts = accounts;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Set<Account> getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set<Account> accounts) {
        this.accounts = accounts;
    }




}


