package in.credit.model;
// Generated Apr 13, 2015 1:34:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Deposit generated by hbm2java
 */
public class Deposit  implements java.io.Serializable {


     private int ledgerId;
     private Ledger ledger;
     private Date startDate;
     private Date maturityDate;
     private BigDecimal amount;
     private BigDecimal interestRate;
     private Date created;
     private int term;

    public Deposit() {
    }

	
    public Deposit(Ledger ledger, int term) {
        this.ledger = ledger;
        this.term = term;
    }
    public Deposit(Ledger ledger, Date startDate, Date maturityDate, BigDecimal amount, BigDecimal interestRate, Date created, int term) {
       this.ledger = ledger;
       this.startDate = startDate;
       this.maturityDate = maturityDate;
       this.amount = amount;
       this.interestRate = interestRate;
       this.created = created;
       this.term = term;
    }
   
    public int getLedgerId() {
        return this.ledgerId;
    }
    
    public void setLedgerId(int ledgerId) {
        this.ledgerId = ledgerId;
    }
    public Ledger getLedger() {
        return this.ledger;
    }
    
    public void setLedger(Ledger ledger) {
        this.ledger = ledger;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getMaturityDate() {
        return this.maturityDate;
    }
    
    public void setMaturityDate(Date maturityDate) {
        this.maturityDate = maturityDate;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public int getTerm() {
        return this.term;
    }
    
    public void setTerm(int term) {
        this.term = term;
    }




}


