package in.credit.model;
// Generated Apr 13, 2015 1:34:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LedgerType generated by hbm2java
 */
public class LedgerType  implements java.io.Serializable {


     private Integer ledgerTypeId;
     private String ledgerTypeName;
     private Set<Ledger> ledgers = new HashSet<Ledger>(0);

    public LedgerType() {
    }

	
    public LedgerType(String ledgerTypeName) {
        this.ledgerTypeName = ledgerTypeName;
    }
    public LedgerType(String ledgerTypeName, Set<Ledger> ledgers) {
       this.ledgerTypeName = ledgerTypeName;
       this.ledgers = ledgers;
    }
   
    public Integer getLedgerTypeId() {
        return this.ledgerTypeId;
    }
    
    public void setLedgerTypeId(Integer ledgerTypeId) {
        this.ledgerTypeId = ledgerTypeId;
    }
    public String getLedgerTypeName() {
        return this.ledgerTypeName;
    }
    
    public void setLedgerTypeName(String ledgerTypeName) {
        this.ledgerTypeName = ledgerTypeName;
    }
    public Set<Ledger> getLedgers() {
        return this.ledgers;
    }
    
    public void setLedgers(Set<Ledger> ledgers) {
        this.ledgers = ledgers;
    }




}


