package in.credit.model;
// Generated Apr 24, 2015 9:08:10 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * LoanInstallment generated by hbm2java
 */
public class LoanInstallment  implements java.io.Serializable {


     private Integer instId;
     private Ledger ledger;
     private long instAmount;
     private Date instDate;
     private Date paidDate;

    public LoanInstallment() {
    }

    public LoanInstallment(Ledger ledger, long instAmount, Date instDate, Date paidDate) {
       this.ledger = ledger;
       this.instAmount = instAmount;
       this.instDate = instDate;
       this.paidDate = paidDate;
    }
   
    public Integer getInstId() {
        return this.instId;
    }
    
    public void setInstId(Integer instId) {
        this.instId = instId;
    }
    public Ledger getLedger() {
        return this.ledger;
    }
    
    public void setLedger(Ledger ledger) {
        this.ledger = ledger;
    }
    public long getInstAmount() {
        return this.instAmount;
    }
    
    public void setInstAmount(long instAmount) {
        this.instAmount = instAmount;
    }
    public Date getInstDate() {
        return this.instDate;
    }
    
    public void setInstDate(Date instDate) {
        this.instDate = instDate;
    }
    public Date getPaidDate() {
        return this.paidDate;
    }
    
    public void setPaidDate(Date paidDate) {
        this.paidDate = paidDate;
    }




}


