package in.credit.model;
// Generated Apr 24, 2015 9:08:10 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Loan generated by hbm2java
 */
public class Loan  implements java.io.Serializable {


     private int ledgerId;
     private Ledger ledger;
     private Date startDate;
     private Date endDate;
     private BigDecimal amount;
     private BigDecimal interestRate;
     private Integer installment;
     private Date created;

    public Loan() {
    }

	
    public Loan(Ledger ledger) {
        this.ledger = ledger;
    }
    public Loan(Ledger ledger, Date startDate, Date endDate, BigDecimal amount, BigDecimal interestRate, Integer installment, Date created) {
       this.ledger = ledger;
       this.startDate = startDate;
       this.endDate = endDate;
       this.amount = amount;
       this.interestRate = interestRate;
       this.installment = installment;
       this.created = created;
    }
   
    public int getLedgerId() {
        return this.ledgerId;
    }
    
    public void setLedgerId(int ledgerId) {
        this.ledgerId = ledgerId;
    }
    public Ledger getLedger() {
        return this.ledger;
    }
    
    public void setLedger(Ledger ledger) {
        this.ledger = ledger;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }
    public Integer getInstallment() {
        return this.installment;
    }
    
    public void setInstallment(Integer installment) {
        this.installment = installment;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


