package in.credit.model;
// Generated Apr 13, 2015 1:34:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Recurring generated by hbm2java
 */
public class Recurring  implements java.io.Serializable {


     private int ledgerId;
     private Ledger ledger;
     private Date startDate;
     private Integer frequency;
     private Integer term;
     private Date endDate;
     private BigDecimal amount;
     private BigDecimal interestRate;
     private Date created;

    public Recurring() {
    }

	
    public Recurring(Ledger ledger) {
        this.ledger = ledger;
    }
    public Recurring(Ledger ledger, Date startDate, Integer frequency, Integer term, Date endDate, BigDecimal amount, BigDecimal interestRate, Date created) {
       this.ledger = ledger;
       this.startDate = startDate;
       this.frequency = frequency;
       this.term = term;
       this.endDate = endDate;
       this.amount = amount;
       this.interestRate = interestRate;
       this.created = created;
    }
   
    public int getLedgerId() {
        return this.ledgerId;
    }
    
    public void setLedgerId(int ledgerId) {
        this.ledgerId = ledgerId;
    }
    public Ledger getLedger() {
        return this.ledger;
    }
    
    public void setLedger(Ledger ledger) {
        this.ledger = ledger;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Integer getFrequency() {
        return this.frequency;
    }
    
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }
    public Integer getTerm() {
        return this.term;
    }
    
    public void setTerm(Integer term) {
        this.term = term;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public BigDecimal getInterestRate() {
        return this.interestRate;
    }
    
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


