package in.credit.model;
// Generated Apr 24, 2015 9:08:10 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * State generated by hbm2java
 */
public class State  implements java.io.Serializable {


     private Integer stateId;
     private String stateName;
     private Set<City> cities = new HashSet<City>(0);

    public State() {
    }

	
    public State(String stateName) {
        this.stateName = stateName;
    }
    public State(String stateName, Set<City> cities) {
       this.stateName = stateName;
       this.cities = cities;
    }
   
    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public Set<City> getCities() {
        return this.cities;
    }
    
    public void setCities(Set<City> cities) {
        this.cities = cities;
    }




}


