package in.credit.model;
// Generated Apr 24, 2015 9:08:10 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount  implements java.io.Serializable {


     private Integer userId;
     private Role role;
     private String userEmail;
     private String userPass;
     private Date created;
     private Date updated;
     private Boolean isDeleted;
     private Boolean isActivate;
     private Date lastLogin;
     private Account accountByUserId;
     private Set<Account> accountsForCreatedBy = new HashSet<Account>(0);
     private Set<Account> accountsForReferenceId = new HashSet<Account>(0);

    public UserAccount() {
    }

	
    public UserAccount(Role role, String userEmail, String userPass) {
        this.role = role;
        this.userEmail = userEmail;
        this.userPass = userPass;
    }
    public UserAccount(Role role, String userEmail, String userPass, Date created, Date updated, Boolean isDeleted, Boolean isActivate, Date lastLogin, Account accountByUserId, Set<Account> accountsForCreatedBy, Set<Account> accountsForReferenceId) {
       this.role = role;
       this.userEmail = userEmail;
       this.userPass = userPass;
       this.created = created;
       this.updated = updated;
       this.isDeleted = isDeleted;
       this.isActivate = isActivate;
       this.lastLogin = lastLogin;
       this.accountByUserId = accountByUserId;
       this.accountsForCreatedBy = accountsForCreatedBy;
       this.accountsForReferenceId = accountsForReferenceId;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Date getUpdated() {
        return this.updated;
    }
    
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    public Boolean getIsDeleted() {
        return this.isDeleted;
    }
    
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
    public Boolean getIsActivate() {
        return this.isActivate;
    }
    
    public void setIsActivate(Boolean isActivate) {
        this.isActivate = isActivate;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Account getAccountByUserId() {
        return this.accountByUserId;
    }
    
    public void setAccountByUserId(Account accountByUserId) {
        this.accountByUserId = accountByUserId;
    }
    public Set<Account> getAccountsForCreatedBy() {
        return this.accountsForCreatedBy;
    }
    
    public void setAccountsForCreatedBy(Set<Account> accountsForCreatedBy) {
        this.accountsForCreatedBy = accountsForCreatedBy;
    }
    public Set<Account> getAccountsForReferenceId() {
        return this.accountsForReferenceId;
    }
    
    public void setAccountsForReferenceId(Set<Account> accountsForReferenceId) {
        this.accountsForReferenceId = accountsForReferenceId;
    }




}


